#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"
ALL_MD_FILE="$(mktemp)"

cleanup() {
  rm -f "$ALL_MD_FILE"
}
trap cleanup EXIT

find . -type f -name '*.md' \
  -not -path './node_modules/*' \
  -not -path './.git/*' \
  | sed 's|^\./||' \
  | sort > "$ALL_MD_FILE"

print_link() {
  local path="$1"
  local link_target

  case "$path" in
    docs/*)
      link_target="./${path#docs/}"
      ;;
    *)
      link_target="../$path"
      ;;
  esac

  printf -- "- [%s](%s)\n" "$path" "$link_target"
}

generate_docs_index() {
  mkdir -p docs

  {
    echo "# Project Index"
    echo
    echo "Master navigation file for this repository."
    echo
    echo "_Auto-generated by \`scripts/sync-markdown.sh\`._"
    echo
    echo "## Root Markdown Files"

    local root_count=0
    while IFS= read -r path; do
      case "$path" in
        */*)
          continue
          ;;
      esac
      print_link "$path"
      root_count=$((root_count + 1))
    done < "$ALL_MD_FILE"

    if [ "$root_count" -eq 0 ]; then
      echo "- (none)"
    fi

    echo
    echo "## Docs Markdown Files"

    local docs_count=0
    while IFS= read -r path; do
      case "$path" in
        docs/*)
          print_link "$path"
          docs_count=$((docs_count + 1))
          ;;
      esac
    done < "$ALL_MD_FILE"

    if [ "$docs_count" -eq 0 ]; then
      echo "- (none)"
    fi

    echo
    echo "## Other Markdown Files"

    local other_count=0
    while IFS= read -r path; do
      case "$path" in
        */*)
          case "$path" in
            docs/*)
              continue
              ;;
          esac
          print_link "$path"
          other_count=$((other_count + 1))
          ;;
      esac
    done < "$ALL_MD_FILE"

    if [ "$other_count" -eq 0 ]; then
      echo "- (none)"
    fi
  } > docs/index.md
}

generate_docs_index

echo "Markdown sync completed at $TIMESTAMP"
